workflows:
  hello-world:
    name: Hello world workflow
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.aladia.io.app
      flutter: stable
      xcode: latest
    instance_type: mac_mini_m1
    max_build_duration: 100
    triggering:
      events:
        - push
    scripts:
      - script: keychain initialize
      - script: keychain add-certificates
      - script: keychain add-provisioning-profile
      - script: xcode-project use-profiles
      - script: flutter packages pub get
      - name: Flutter build ipa
        script: |
          flutter build ipa
      - name: Build apk
        script: flutter build apk --release
      - name: Build ios
        script: flutter build ios --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - biniyhaile@gmail.com
